// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQNsxU_HLKdy8WXd3-QA25R6_dMv5uXQ',
    appId: '1:714369473512:web:bda47ce1adc0834ea9a25d',
    messagingSenderId: '714369473512',
    projectId: 'chatapp-740cc',
    authDomain: 'chatapp-740cc.firebaseapp.com',
    storageBucket: 'chatapp-740cc.appspot.com',
    measurementId: 'G-TNCZRVHHM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr49fdgp13tPPbU5-BGPVeD_Yu_8gSFYI',
    appId: '1:714369473512:android:83653cada9f29ccda9a25d',
    messagingSenderId: '714369473512',
    projectId: 'chatapp-740cc',
    storageBucket: 'chatapp-740cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLGohn3ECHHphnBOY4BWRY1n9jq5h15MQ',
    appId: '1:714369473512:ios:f369b5e8ed96b455a9a25d',
    messagingSenderId: '714369473512',
    projectId: 'chatapp-740cc',
    storageBucket: 'chatapp-740cc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLGohn3ECHHphnBOY4BWRY1n9jq5h15MQ',
    appId: '1:714369473512:ios:0f1d99f8b6ea8a1ca9a25d',
    messagingSenderId: '714369473512',
    projectId: 'chatapp-740cc',
    storageBucket: 'chatapp-740cc.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
